### ISSUE TITLE
Not working with new Firefox

### ISSUE THREAD

**Issue by noahmaes** [rzelazko/grabthemall#10]
I loved this plugin, unfortunately the plugin is not working with the new Firefox - is there a way to get this fixed?

**Comment by sladams224** [comment]
Would also like to know how I could use this plugin again. It's perfect for some very tedious tasks at work and I haven't found anything that works as well. If anyone knows how to get this plugin working now or knows of a different low- or no-code resource for acquiring screenshots based on a list of URLs, please share.

**Comment by rzelazko** [comment]
I am sorry but I do not have time to maintain this plugin. It would require to be rewritten from scratch to make it available on modern browsers. I am pretty sure though there are some modern alternatives which will meet your needs.
